const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'Shirt',
      image: '/images/Shirt2.jpg',
      price: 90,
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'smart looking pants',
    },
    {
      name: 'Fit Pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'smart looking pants',
    },
  ],
};
