const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'smart looking pants',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'smart looking pants',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'smart looking pants',
    },
    {
      name: 'Golf Pants',
      category: 'Pants',
      image: '/images/pants.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      CountInStock: 20,
      description: 'smart looking pants',
    },
  ],
};
